""" Define algorithm parameters here """

GENERATION_SIZE = 1000
POPULATION_SIZE = 500
FILE_NAME = "data_tsp.txt"
MUTATION_CHANCE = 0.04
CROSSOVER_SIZE = 5
ELITISM_RATE = 0.03
CHROMOSOME_MAX_AGE = 5
CITIES = {}