
FILE_NAME = "data/data_tsp.txt"
NUM_GENERATIONS = 2000
POPULATION_SIZE = 520
TOURNAMENT_SELECTION_SIZE = 5
MUTATION_CHANCE = 0.3
ELITISM_RATE = 0.02
RESET_RATE = 0.2
CHROMOSOME_MAX_AGE = 30
CITIES = {}
