""" Define algorithm parameters here """

FILE_NAME = "data/data_tsp.txt"
NUM_GENERATIONS = 3000
POPULATION_SIZE = 520
TOURNAMENT_SELECTION_SIZE = 10
MUTATION_CHANCE = 0.03
ELITISM_RATE = 0.005
CHROMOSOME_MAX_AGE = 8
CITIES = {}